Repository SE-8-2021/backend, pull requests merged in 2022-01, with the labels that each got.

#34 Fix: Prevent getting issues/pull requests from GitHub failed
  src/main/java/pvs/app/controller/GithubApiController.java
Labels: bug

#36 fix: Prevent error of branch names containing symbols
  src/main/java/pvs/app/controller/GitLabApiController.java
  src/main/java/pvs/app/controller/GithubApiController.java
Labels: bug

#37 Fix: Make different accounts can see different projects
  src/main/java/pvs/app/controller/AuthController.java
  src/main/java/pvs/app/dto/CreateProjectDTO.java
  src/main/java/pvs/app/service/AuthService.java
  src/main/java/pvs/app/service/ProjectService.java
  src/test/java/pvs/app/service/AuthServiceTest.java
Labels: bug

#38 feat: Add register function
  pom.xml
  src/main/java/pvs/app/config/SecurityConfig.java
  src/main/java/pvs/app/controller/AuthController.java
  src/main/java/pvs/app/service/AuthService.java
Labels: enhancement

#42 fix: Issue data out of buffer
  src/main/java/pvs/app/service/GithubApiService.java
  src/main/java/pvs/app/service/thread/GithubIssueLoaderThread.java
Labels: bug

#46 fix: Password validation error
  src/main/java/pvs/app/controller/AuthController.java
  src/main/java/pvs/app/service/AuthService.java
Labels: bug

#47 refactor: remove duplicate DTO and rename files and variables
  src/main/java/pvs/app/controller/GitLabApiController.java
  src/main/java/pvs/app/controller/GithubApiController.java
  src/main/java/pvs/app/controller/ProjectController.java
  src/main/java/pvs/app/dto/AddGitLabRepositoryDTO.java
  src/main/java/pvs/app/dto/AddRepositoryDTO.java
  src/main/java/pvs/app/dto/AddSonarRepositoryDTO.java
  src/main/java/pvs/app/dto/AddTrelloBoardDTO.java
  src/main/java/pvs/app/dto/CommitDTO.java
  src/main/java/pvs/app/dto/GitLabCommitDTO.java
  src/main/java/pvs/app/service/GitLabCommitService.java
  src/main/java/pvs/app/service/GithubCommitService.java
  src/main/java/pvs/app/service/ProjectService.java
  src/main/java/pvs/app/service/thread/GitLabCommitLoaderThread.java
  src/main/java/pvs/app/service/thread/GithubCommitLoaderThread.java
  src/test/java/pvs/app/service/GithubCommitServiceTest.java
Labels: Refactor

#48 Refactor: Remove MemberService and RoleService
  src/main/java/pvs/app/controller/MemberController.java
  src/main/java/pvs/app/dao/RoleDAO.java
  src/main/java/pvs/app/dto/RoleDTO.java
  src/main/java/pvs/app/entity/Member.java
  src/main/java/pvs/app/entity/Role.java
  src/main/java/pvs/app/service/MemberService.java
  src/main/java/pvs/app/service/RoleService.java
  src/test/java/pvs/app/dao/RoleDAOIntegrationTest.java
  src/test/java/pvs/app/service/AuthServiceTest.java
  src/test/java/pvs/app/service/MemberServiceTest.java
  src/test/java/pvs/app/service/RoleServiceTest.java
  src/test/java/pvs/app/service/impl/UserDetailServiceImplTest.java
  src/test/java/pvs/app/service/utils/JwtTokenUtilTest.java
Labels: Refactor

#49 Refactor adding repository
  src/main/java/pvs/app/controller/ProjectController.java
  src/main/java/pvs/app/controller/RepositoryController.java
Labels: Refactor

#43 Feat: Add functions of rename project
  src/main/java/pvs/app/controller/ProjectController.java
  src/main/java/pvs/app/dao/ProjectDAO.java
  src/main/java/pvs/app/entity/Project.java
  src/main/java/pvs/app/service/ProjectService.java
Labels: enhancement
